[package]
name = "promiscope-verification"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
promiscope-shared-types = { path = "../shared-types" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
promiscope-progress = { path = "../progress" }
ed25519-dalek = { workspace = true }
